# Generated by Django 4.2.7 on 2025-05-29 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('confirmed', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('pets', models.JSONField(default=list)),
                ('petsitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.petsitter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visit',
            },
        ),
    ]
