# Generated by Django 4.2.7 on 2025-05-28 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petsitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('is_dog_sitter', models.BooleanField(default=False)),
                ('is_cat_sitter', models.BooleanField(default=False)),
                ('is_rodent_sitter', models.BooleanField(default=False)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('care_at_owner_home', models.BooleanField(default=False)),
                ('care_at_petsitter_home', models.BooleanField(default=False)),
                ('dog_walking', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='petsitter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetsitterAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('petsitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='api.petsitter')),
            ],
        ),
    ]
