# Generated by Django 4.2.7 on 2025-10-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_email_alter_pet_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
