version: '3.8'

services:
  backend:
    build: ./petzone_backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Usuń mapowanie wolumenu developmentowego
    # volumes:
    #   - ./petzone_backend:/app

  frontend:
    stdin_open: true
    build: ./petzone_frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
