version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/petzone_backend:/app/petzone_backend
    networks:
      - petzone_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/petzone_frontend:/app/petzone_frontend
    networks:
      - petzone_network

networks:
  petzone_network:
    driver: bridge
